### ISSUE TITLE
sudo ajenti-dev-multitool command not found

### ISSUE THREAD

**Issue by vireakvibol** [ajenti/ajenti-dev-multitool#17]
Hello i'm installing **ajenti-dev-multitool** without **root** with command
`pip3 install ajenti-dev-multitool`

if running the with **normal user without sudo** `ajenti-dev-multitool --help` is working.
But running with `sudo ajenti-dev-multitool` return command not found
| Component | Version |
| --- | --- |
| OS | Almalinux 8.6 |
| python | 3.6.8 |
| pip | 21.3.1

I can't clarify if the problem persist on other OS or not because currently my main development OS is **almalinux 8.6**

**Comment by kiarn** [comment]
Hello,

I think you need to install it as superuser.

Arnaud

**Comment by vireakvibol** [comment]
@kiarn if install it as super user `sudo pip3 install ajenti-dev-multitool` all user will can't access to `ajenti-dev-multitool`.
Command `ajenti-dev-multitool` not found on every user even `sudo ajenti-dev-multitool` still produce **command not found**. I will test order OS like **debian** or **ubuntu** if i have time but not really sure is it possible yet.

**Comment by kiarn** [comment]
Hello @vireakvibol 

What's the problem if all users can access `ajenti-dev-multitool` on your dev environment ?
Another possibility is simply to checkout the multitool repository and to create a symlink in `/usr/local/bin`, that's what I do on my dev server. This way I always work with the latest version.

Arnaud

**Comment by kiarn** [comment]
The new tools for angular are now available in the [ajenti-3-dev](https://github.com/ajenti/ajenti-dev-multitool/tree/ajenti-3-dev) branch.

**Comment by vireakvibol** [comment]
I rebootstrap my dev invironment again with almalinux 8 and ubuntu 22.04 and let see is there any problem again. I will follow your suggestion.

Thank you

**Comment by kiarn** [comment]
Hello @vireakvibol 

Did you succeed to use it, or do you need more help ?
